version: '3.7'
services:
  njsc_redis:
    image: redis:5.0.2
    ports:
      - 6379:6379
  njsc_api:
    image: danstory/njsc_api:dev
    build:
      context: .
      dockerfile: ./Dockerfile
    command: api --redis redis://njsc_redis:6379
    depends_on:
      - njsc_redis
    ports:
      - 8888:3000
  njsc_worker:
    image: danstory/njsc_api:dev
    build:
      context: .
      dockerfile: ./Dockerfile
    command: worker --redis redis://njsc_redis:6379
    depends_on:
      - njsc_redis